
version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: build1
      buildspec: build2.yml
      
      env:
        variables:
          BUILD_ID: build1
          source: "https://github.com/kunal3237/JavacodeforPractice3.git"
          target: "kunalcodebuildtargets3/build2/"
        compute-type: BUILD_LAMBDA_1GB
        type: ARM_LAMBDA_CONTAINER
        image: aws/codebuild/amazonlinux-aarch64-lambda-standard:corretto21
      depend-on: 
        - build1
    - identifier: build2
      
      env:
         variables:
           BUILD_ID: build2
           source: "https://github.com/kunal3237/JavacodeforPractice3.git"
           target: "kunalcodebuildtargets3/build2/"
    # dynamic:
    #  buildspec: 
    #    - build2.yml
    #    - buildspec.yaml
    #  env:  
    #    variables:
    #      source: 
    #        - "https://github.com/kunal3237/JavacodeforPractice3.git"
    #  #   compute-type: BUILD_LAMBDA_1GB  
    

phases:
  
  post_build:
    commands:
      - echo Both Build completed on `date` ${BUILD_ID}
      - ls
      - git clone ${source}
