version: 0.2

batch:
  fast-fail: false
  build-list:
    # - identifier: build1
    #   buildspec: build1.yml
    #   env:
    #     variables:
    #       BUILD_ID: build1
    #       source: "https://github.com/kunal3237/JavacodeforPractice1.git"
    #       target: kunalcodebuildtargets3/build1/
    - identifier: build2
      buildspec: build2.yml
      env:
        variables:
          BUILD_ID: build2
          #source: https://github.com/kunal3237/JavacodeforPractice2.git
          #target: kunalcodebuildtargets3/build2/  
      
    

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - echo Both Build completed on `date` ${BUILD_ID}

